### ISSUE TITLE
Problem while executing experiment for 128 section with 7 days long period

### ISSUE THREAD

**Issue by mkasztelnik** [ismop/dap#2]
Following error is thrown every time I'm trying to run experiment for 128 sections, for 7 days. @nowakowski, @bwilk please take a look - I need to execute such experiment for iccs publication (so it should be fixed quite fast - paper deadline is end of next week and I need to interpret the results and write article section).

```
I, [2015-01-23T14:41:58.476938 #11216]  INFO -- :   Parameters: {"sensor_id"=>["411", "412", "413", "414", "415", "416", "417", "418", "419", "420"], "time_from"=>"2015-01-14 09:45:42 +0100", "time_to"=>"2015-01-21 09:45:42 +0100", "measurement"=>{}}
I, [2015-01-23T14:41:58.489423 #11216]  INFO -- : Started GET "/api/v1/measurements/?sensor_id%5B%5D=421&sensor_id%5B%5D=422&sensor_id%5B%5D=423&sensor_id%5B%5D=424&sensor_id%5B%5D=425&sensor_id%5B%5D=426&sensor_id%5B%5D=427&sensor_id%5B%5D=428&sensor_id%5B%5D=429&sensor_id%5B%5D=430&time_from=2015-01-14+09%3A45%3A42+%2B0100&time_to=2015-01-21+09%3A45%3A42+%2B0100" for 127.0.0.1 at 2015-01-23 14:41:58 +0100
I, [2015-01-23T14:42:04.513925 #11216]  INFO -- : Completed 200 OK in 23038ms (Views: 22045.5ms | ActiveRecord: 981.7ms)
F, [2015-01-23T14:42:04.580104 #11216] FATAL -- : 
ActiveRecord::ConnectionTimeoutError (could not obtain a database connection within 5.000 seconds (waited 5.004 seconds)):
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:190:in `block in wait_poll'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `loop'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:181:in `wait_poll'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:136:in `block in poll'
  /home/servers/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:146:in `synchronize'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:134:in `poll'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:418:in `acquire_connection'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:351:in `block in checkout'
  /home/servers/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:350:in `checkout'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:265:in `block in connection'
  /home/servers/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:264:in `connection'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_handling.rb:87:in `connection'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/query_cache.rb:32:in `call'
  vendor/bundle/ruby/2.1.0/gems/activerecord-4.1.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/callbacks.rb:82:in `run_callbacks'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:38:in `call_app'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/tagged_logging.rb:68:in `tagged'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.1.0/gems/actionpack-4.1.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/2.1.0/gems/activesupport-4.1.1/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  vendor/bundle/ruby/2.1.0/gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/engine.rb:514:in `call'
  vendor/bundle/ruby/2.1.0/gems/railties-4.1.1/lib/rails/application.rb:144:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/configuration.rb:71:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:490:in `handle_request'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:361:in `process_client'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/server.rb:254:in `block in run'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/thread_pool.rb:92:in `call'
  vendor/bundle/ruby/2.1.0/gems/puma-2.8.1/lib/puma/thread_pool.rb:92:in `block in spawn_thread'

```

**Comment by nowakowski** [comment]
@mkasztelnik Did you use dap or dap-dev?

**Comment by nowakowski** [comment]
@mkasztelnik If it's dap-dev (as I suspect it is), try it again - I have increased the connection pool size.

**Comment by mkasztelnik** [comment]
Yuap `dap-dev` is used to run experiments. I just started a new one (id `115`)

**Comment by mkasztelnik** [comment]
Great it helped :) Thank you for your help
